backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "giftcard"
      name: "giftcard"
      file: "content/giftcard.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Body", name: "body", widget: "markdown"}
    - label: "helpcenter"
      name: "helpcenter"
      file: "content/helpcenter.md"
      fields:        
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Body", name: "body", widget: "markdown"}
        - label: 'Contact'
          name: "Contact"
          widget: list
          fields:
            - { label: "Country", name: "country", widget: "string"}
            - { label: "Contact nO", name: "ContactNo", widget: "text"}

    
        